version: "3.7"

services:
  db:
    container_name: "foodie_db"
    image: "postgres:12"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=foodie
      - POSTGRES_USER=foodie
      - POSTGRES_PASSWORD=qwerty
  web:
    container_name: "foodie_web"
    build: .
    command: ./gradlew bootRun
    environment:
      - spring_profiles_active=docker
      - DB_HOST=db
      - INIT_DB=false
      - SERVER_PORT=8080
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - "15800:8080" # host:container
    restart: always