server:
  port: ${SERVER_PORT:8080}
logging:
  level:
    web: "info"
management:
  trace:
    http:
      include: RESPONSE_HEADERS
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:postgresql://${DB_HOST}:5432/foodie"
    username: "foodie"
    password: "qwerty"
  flyway:
    enabled: true
    url: "jdbc:postgresql://${DB_HOST}:5432/foodie"
    user: "foodie"
    password: "qwerty"
  jpa:
    show-sql: true