server:
  port: 8080
logging:
  level:
    web: "debug"
management:
  endpoints:
    web:
      exposure:
        exclude: "*"
spring:
  h2:
    console:
      enabled: false
  datasource:
    url: "jdbc:h2:file:./h2/test"
    driver-class-name: "org.h2.Driver"
    username: "postgres"
    password: "qwerty"
  flyway:
    enabled: true
    url: "jdbc:h2:file:./h2/test"
    user: "postgres"
    password: "qwerty"
  jpa:
    hibernate:
      ddl-auto: "none"
    show-sql: true